openapi: 3.0.1
info:
  title: testing
  description: ansible utils
  version: 0.9.1

servers:
  - url: /

paths:
  /api/v1/whoami:
    get:
      summary: fetch a username
      description: return the username as json
      parameters:
          - in: query
            name: user
            required: true

      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /api/v1/version:
    get:
      summary: get linux version of localhost
      description: get linux version
      parameters:
          - in: query
            name: hostname
            required: false
            example: 'localhost'
            default: 'localhost'
      responses:
        '200':    # status code
          description: linux version
          content:
            application/json:
              schema: 
                  $ref: '#/components/schemas/linux_version'
security:
  - bearerAuth: [] 
   
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

  schemas:
    linux_version:
      type: object
      properties:
          hostname:
             type: object
             properties:
                version:
                    type: string
